# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ad və Soyadı')),
                ('universitet', models.CharField(max_length=255, verbose_name='Universitet')),
                ('kurs', models.CharField(max_length=255, verbose_name='Kurs')),
                ('group', models.CharField(max_length=255, verbose_name='Qrup')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('number', models.CharField(max_length=255, verbose_name='Nomre')),
                ('text', models.TextField(verbose_name='Əlavə məlumat')),
                ('types', models.IntegerField(choices=[(1, 'Bir üzlü'), (2, 'Iki üzlü')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Sifarişçilər',
                'verbose_name': 'Sifarişçi',
                'ordering': ('-id',),
            },
        ),
    ]
