# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
