# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 23:15
from __future__ import unicode_literals

import center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20170203_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to=center.models.filedirectory)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
