# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20170203_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.Orders'),
        ),
    ]
