# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_auto_20170209_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='check_telebe',
            field=models.IntegerField(blank=True, choices=[(1, 'tələbə'), (2, 'Fiziki şəxs')], null=True, verbose_name='Universitet'),
        ),
        migrations.AddField(
            model_name='orders',
            name='listed',
            field=models.IntegerField(blank=True, choices=[(1, 'Ağ-qara'), (2, 'Rəngli')], null=True, verbose_name='Universitet'),
        ),
    ]
