# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_auto_20170209_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='check_telebe',
            field=models.IntegerField(blank=True, choices=[(1, 'tələbə'), (2, 'Fiziki şəxs')], null=True, verbose_name='Tələbəsiniz'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='types',
            field=models.IntegerField(choices=[(1, 'Bir üzlü'), (2, 'Iki üzlü')], default=1, verbose_name='Vərəqin növü'),
        ),
    ]
